openapi: 3.0.3
info:
  title: Common Nomenclature under Article 6.2 of the Paris Agreement
  version: v0.01
  description: |
     This document presents the common list of values for specific information attributes required for the reporting of annual information in accordance Article 6.2 of the Paris Agreement.
     It includes the list of common values necessary for the reporting in the draft version of the AEF as contained in Annex VII of Decision 6/CMA.4
  contact: 
    name: UNFCCC secretariat (Voluntary forum of Article 6 registry system administrators and technical experts)
    email: a6rsaf@unfccc.int
    url: https://www.unfccc.int
  license: 
    name: N/A
    url: N/A
  x-audience: external-public
  x-api-id: unused-for-this-api-0
paths:
  /accountType:
    get:
      tags:
        - accountType
      operationId: getAccountType
      description: |
        Returns the valid values for Account Type
        from the Common Nomenclature under Article 6.2 of the Paris Agreement
        
        * 1 - Issuance
        * 10 - Internal transfer
        * 3 - External transfer
        * 4 - Cancellation
        * 5 - "Use towards NDC - Referred to as Retirement"
        * 7 - "Change of authorisation - Referred to as Carry-over"
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountType'
  
  /participatingParty:
    get:
      tags:
        - participatingParty
      operationId: getParticipatingParty
      description: |
        Returns the valid values for Participating Party
        from the Common Nomenclature under Article 6.2 of the Paris Agreement
        
        ISO-3166 3 letter code of the country
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/participatingParty'

  /transactionType:
    get:
      tags:
        - transactionType
      operationId: getTransactionType
      description: |
        Returns the valid values for Transaction Type
        from the Common Nomenclature under Article 6.2 of the Paris Agreement
        
        See also suppTransactionType regarding first transfers.
        * 1 - Issuance
        * 10 - Internal transfer
        * 3 - External transfer
        * 4 - Cancellation
        * 5 - "Use towards NDC - Referred to as Retirement"
        * 7 - "Change of authorisation - Referred to as Carry-over"
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transactionType'
  /unitType:
    get:
      tags:
        - testUnitType
      operationId: testUnitType
      description: |
        Returns whether a value is a valid for Unit Type
        from the Common Nomenclature under Article 6.2 of the Paris Agreement
        
        * 62 - ITMO
        * 64 - A6.4ER
        * 65 - A6.4ER from CER
        * 67 - MCU
      parameters:
        - name: value
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/unitType'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unitType'
components:
  schemas:
    accountType:
      description: |
        Account types under Article 6.
        * 100 - Holding account.  Must be used as a destination of issuance(s),
                  or as a source or destination of internal or external transfer,
                  or as a source of cancellations or use
        * 110 - Pending account
        * 120 - Operator holding account
        * 121 - Person holding account
        * 230 - Voluntary cancellation account
        * 250 - Mandatory cancellation account for OMGE
        * 280 - Voluntary cancellation account for OMGE
        * 270 - Use towards other purposes account
        * 300 - Use towards NDC account
      type: integer
      enum:
        - 100
        - 110
        - 120
        - 121
        - 230
        - 250
        - 280
        - 270
        - 300
    participatingParty:
      description: ISO-3166 3 letter code of the country
      type: string
    transactionType:
      description: |
        Transaction types under Article 6.  See also suppTransactionType regarding first transfers.
        See also suppTransactionType regarding first transfers.
        * 1 - Issuance
        * 10 - Internal transfer
        * 3 - External transfer
        * 4 - Cancellation
        * 5 - "Use towards NDC - Referred to as Retirement"
        * 7 - "Change of authorisation - Referred to as Carry-over"
      type: integer
      enum:
        - 1
        - 10
        - 3
        - 4
        - 5
        - 7
    unitType:
      description: |
        Unit types under Article 6.
        * 62 - ITMO
        * 64 - A6.4ER
        * 65 - A6.4ER from CER
        * 67 - MCU
      type: integer
      enum:
        - 62
        - 64
        - 65
        - 67
  
