openapi: 3.0.3
info:
  title: API for transactions with ITMOs (Work In Progress)
  description: 
     <b>Introduction</b>
     <br><br>This API is part of the communication standards for transactions with
     Internationally Transferred Mitigation Outcomes (ITMOs) pursuant to decision 6/CMA.4, para. 32.
     <br><br>Participating Parties opting to apply the guidance referred to in 
     decision 6/CMA.4, annex I, chapter I.B are expected to adhere to this API when they interoperate.
     <br><br><b>Current status</b>
     <br><br>This API is currently limited to schema definitions for ITMOs.
  version: 0.0.1
  contact: 
    name: UNFCCC secretariat (Voluntary forum of Article 6 registry system administrators and technical experts)
    email: a6rsaf@unfccc.int
    url: https://www.unfccc.int
  license: 
    name: N/A
    url: N/A
  x-audience: external-public
  x-api-id: unused-for-this-api-0
servers:
  - url: TBD
    description: Production server (uses live data !)
  - url: TBD
    description: Test server (uses test data)
paths: 

  /status:
    get:
      tags:
        - Status
      operationId: getStatus
      summary: Retrieve the status of the server
      description: Retrieve the status of the server
      responses:
        '200':
          description: Successful operation.
          content:
            application/problem+json: # According to recommended practice, 200 returns a problem json with positive code for /status
              schema:
                $ref: '#/components/schemas/ErrorOrWarningResponse'
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorOrWarningResponse'

components:
  schemas:
    ITMO:
      type: object
      required:
        - cooperativeApproach
        - originatingPartyRegistry
        - firstID
        - lastID
        - firstTransferringParty
        - vintage
        - mitigationOutcomeHashes
        - sectors
        - activityTypes
        - metric
        - quantityCO2
        - mitigationType
        - authorisationID
      properties:
        cooperativeApproach:
          description: Cooperative approaches under Article 6.2.\nThe format of the string is \"CANNNN\" where the \"CA\" is the fixed prefix, and NNNN is a four-digit integer, that shall be incremented by one for each additional agreed cooperative approach, and added to this common nomenclature.
          type: string
          example: "CA0002"
        orginatingPartyRegistry:
          description: ISO-3166-1 alpha-3 code of the participating Party in which the mitigation outcomes originated.
          type: string
          example: "BEL"
        firstID:
          description: Identifier of the first ITMO in the block, commencing with First ID, ending with Last ID.\nBlocks from the same Originating Party Registry cannot overlap.
          type: integer
          format: int32
          example: 1
        lastID:
          description: Identifier of the last ITMO in the block, commencing with First ID, ending with Last ID.\nBlocks from the same Originating Party Registry cannot overlap.
          # Note: decision 6/CMA.4, annex I, para.5(d) requires a single unique identifier in ITMO identifier,
          # but as all ITMOs are considered as blocks, the last identifier of the block is required.
          type: integer
          format: int32
          example: 7144
        partyITMORegistry:
          description: ISO-3166-1 alpha-3 code of participating party registry currently owns the ITMO(s).
          type: string
          example: "FRA"
        firstTransferringParty:
          description: ISO-3166-1 alpha-3 code of participating party registry that initiates the \"First Transfer\".
            Refer to common nomenclalture for definition of \"First Transfer\".
          type: string
          example: "FRA"
        vintage:
          description: Year in which mitigation outcome occured.
          type: integer
          format: int32
          minimum: 2021
          maximum: 9999
          example: 2025
        mitigationOutcomeHashes:
          description: (required by Decision 6/CMA.4, annex I, para.4). ITMOs must be traceable to their mitigation outcomes.
                  This array contains the SHA256 hashes of all mitigation outcome documents for this ITMO.
                  The UNFCCC will store all MO documents, and provide an API getMitigationOutcomeDoc(originatingPartyRegistry, firstID, lastID, SHA256)
                  that will return the URL of the MO document corresponding to the hash.
          type: array
          items:
            description: SHA256 hash of a single mitigation outcome document
            type: string
            minItems: 1
            example: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        sectors:
          description: One or more sectors where the mitigation outcome occurred as per common nomenclatures based on IPCC guidelines.
            Refer to common nomenclature for recognised values for \"sectors\".
          type: array
          items:
            type: string
        activitytypes:
          description: The mitigation activity type(s) from which the ITMOs were generated.
            Refer to common nomenclature for recognised values for \"activityTypes\".
          type: array
          items:
            type: string
        metric:
          description: The metric used to measure the ITMO.
            As defined in the common nomenclature - recognised values are \"GHG\" and \"non-GHG\".
          type: string
          example: "GHG"
        quantityCO2:
          description: Quantity of ITMOs in metric tons of CO2 equivalent.
          type: integer
          format: int32
          minimum: 1
          maximum: 999999999
          example: 7144362
        gwpValues:
          description: If the mitigation outcome involves a non-CO2 greenhouse gas(es), the global warming potential (GWP) value(s) applied, consistent with the relevant CMA decisions (e.g.,\'100-year values from 5th assessment report by the IPCC\').
          type: string          
        non-GHGMetric:
          description: Type of non-GHG metric applied (e.g., ‘megawatt hours of renewable electricity generation’). This field should be reported as \‘Not applicable\’ (NA) if the ITMOs are in a GHG metric.
          type: string
        quantityNon-GHG:
          description: Quantity of ITMOs in the respective non-GHG metric. This field should be reported as ‘Not applicable’ (NA) if the ITMOs are in a GHG metric.
          type: integer
          format: int32
          minimum: 1
          maximum: 999999999
        mitigationType:
          description: “Emission reductions” or “Removals”
          type: string
          example: Emissions reduction
        isAuthorised:
          description: whether this A6.4ER has been authorised, thus, is an ITMO.  If it is authorised, the cooperativeApproach cannot be CA0000.
          type: boolean
          example: true
        authorisationID:
          description: Authorization ID as assigned by the Party reporting the authorisation.
          type: string
          example: "GUY 2024-CA1"
#  
# Apart from authorisationID, other details from the authorisation of the ITMO(s)
# shall be retrieved from the authorisation transaction log using the authorisation ID.
# These details should not be part of the ITMO object.
#
#        authorisingParty:
#          description: ISO 3166-1 alpha-3 identifier of the authorising Party.  For native ITMOs, it will be the same as the first transferring Party.
#          type: string
#          example: "GUY"
#        authorisationDateTime:
#          description: date-timestamp of the authorisation of A6.4ER, turning it into an ITMO
#          type: string
#          format: date-time
#          example: "2024-07-21T17:32:28Z"
#
        suppInfo:
          description: Any supplementary information the current owning Party may need to attach to the ITMOs
            This should be an append only property.
            Only the current owning Party should be able append supplementary information.
          type: array
          items:
            type: string
            maxLength:  255
        lastanyTxnDateTime:
          description:  Date-timestamp of the last attempted transaction.
          type: string
          format: date-time
          example: "2024-07-21T17:32:28Z"
        lastAcceptedTxnDateTime:
          description:  Date-timestamp of last successful transation.
          type: string
          format: date-time
          example: "2024-07-21T17:32:28Z"
        modifiedDateTime:
          description:  Date-timestamp of last modification of any of the ITMO(s) elements.
            Kept in ITMO instead of relying on hosting system to survive migration across hosting solutions.
          type: string
          format: date-time
          example: "2024-07-21T17:32:28Z"
        createdDateTime:
          description:  Date-timestamp of creation of the ITMO(s).
            Kept in ITMO instead of relying on hosting system to survive migration across hosting solutions.
          type: string
          format: date-time
          example: "2024-07-21T17:32:28Z"

    ErrorOrWarningResponse: # Problem JSON / RFC 7XXX compatible error. See https://opensource.zalando.com/restful-api-guidelines/models/problem-1.0.1.yaml
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://zalando.github.io/problem/constraint-violation'
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the
            problem.
          example: Connection to database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
  securitySchemes:

    basicAuth:
      type: http  #TBD: Open API 3.1 supports mutualTLS
      scheme: basic
      x-registry-secret:
        type: string

security:
  - basicAuth: []
