@startuml getTxnStatus_Sequence

skinparam dpi 300
skinparam monochrome true
skinparam shadowing true

hide footbox
skinparam sequenceMessageAlign center

participant "Registry" as r
participant "Interoperability Hub" as h

r->h: getTxnStatus(txnId, txnStatus)
note left: optionally provide the\nregistry's transaction status
h-->>r: //txnStatus//
note left: returns the hub's\ntransaction status
