@startuml getTransactionStatus flow

skinparam dpi 300
skinparam monochrome true
skinparam shadowing true

hide footbox
skinparam sequenceMessageAlign center

participant "Registry" as r
participant "Interoperability Hub" as h

group Registry to Hub
  r->h: GET /transactionStatus/{id}
  h-->>r: transaction status (OK)
end

group Hub to Registry
  h->r: GET /transactionStatus/{id}
  r-->>h: transaction status (OK)
end
@enduml
