@startuml

title ITMO Lifecycle \n
|Participating Party|

start


    :Cooperative Approach Authorized;
      note left
        decision 2 CMA.3, annex, para 18(g)
        * participating Party authorizes
          Cooperative Approach
      end note
  
    :Party registers
    Cooperative Approach
    authorization;
      note left
        decision 2 CMA.3, annex, para 18
        * Party submits initial report
            to register authorization
        * One or more combinations
            of authorizations of
            Coooperative Approach,
            ITMOs relating to the
            Cooperative Approach, and
            Entities
      end note
    |Secretariat|
    :Secretariat (issuing authority)
    - assigns Authorization Id
    - registers Cooperative Approach
      and authorization
      in CARP and 
      Common Nomenclatures;
      note left
        Authorization Id must be
        assigned by secretariat
        to ensure uniqueness
      end note
    |Participating Party|
    :Party registers 
    ITMO(s) authorization
    with Secretariat;
      note left
          If not already registered
          with Cooperative Approach
          authorization registration
      end note

    |Secretariat|
    :Secretariat
    - assigns Authorization Id
    - registers ITMO(s) authorization
      in CARP;
      note left
        * Authorization Id must be
            assigned by secretariat
            to ensure uniqueness
        * Secretariat will also register 
            authorized entities
      end note

    |Participating Party|
    if (Party opts for Interoperability) then (yes)
  
      |Interoperating Party|
      :First transferring\nparticipating Party\nissues ITMOs;
        note left
        * Use //proposeAction// API
        * Action is Issuance
        * Registry provides account Id
            to hold the ITMO(s)
        * ITMOs will be created in
          the International Registry
        * unique ITMOId will be
          returned to registry
        end note
      |International\nRegistry Hub|
      :Validate Issuance
      and
      provide ITMO Id;

      |Interoperating Party|
      :Finalize Issuance
      and record ITMO Id;
    else (no)
      |Participating Party|
      stop
    
  endif

|Interoperating Party|


  while (Propose Use or Cancel action) is (no)
  
    :Propose other
    actions on ITMOs;
      note left
      Other actions such as
      transfers, updates, ...
      end note
    |International\nRegistry Hub|
    :Validate and
    facilitate
    other actions;
    |Interoperating Party|
    :Finalise other
    actions on ITMOs;
  endwhile (yes)
    |International\nRegistry Hub|
    :Validate and
    facilitate
    Use or Cancel
    action;
    |Interoperating Party|
    :Finalise Use or
    Cancel actions;
    stop

@enduml
