@startuml

title ITMO Lifecycle \n
|Participating Party|

start


    :Cooperative Approach\nAuthorized;
      note left
        Decision 2 CMA.3,
        annex, para 18(g)
        * participating Party authorizes
          Cooperative Approach
      end note
  
    :Party registers
    Cooperative Approach
    authorization;
      note left
        Decision 2 CMA.3,
        annex, para 18
        * Party submits initial report
            to register authorization
        * One or more combinations
            of authorizations of
            Coooperative Approach,
            ITMOs relating to the
            Cooperative Approach, and
            Entities
      end note
    |Secretariat|
    :Secretariat (issuing authority)
    - assigns Authorization Id
    - registers Cooperative Approach
      and authorization
      in CARP and 
      Common Nomenclatures;
      note left
        Authorization Id must be
        assigned by secretariat
        to ensure uniqueness
      end note
    |Participating Party|
    :Party registers 
    ITMO(s) authorization
    with Secretariat;
      note left
          If not already registered
          with Cooperative Approach
          authorization registration
      end note

    |Secretariat|
    :Secretariat
    - assigns Authorization Id
    - registers ITMO(s) authorization
      in CARP;
      note left
        * Authorization Id must be
            assigned by secretariat
            to ensure uniqueness
        * Secretariat will also register 
            authorized entities
      end note

    |Participating Party|
    if (Party opts for Interoperability) then (yes)
  
      |Interoperating Party|
      :First transferring\nparticipating Party\nissues ITMOs;
        note left
        * Use //proposeTxn// API
        * Txn type is Issuance
        * Registry provides account Id
            to hold the ITMO(s)
        * ITMOs will be created in
          the International Registry
        * unique ITMOId will be
          returned to registry
        end note
      |Interoperability\nHub|
      :Validate Issuance
      and
      provide ITMO Id;

      |Interoperating Party|
      :Finalize Issuance
      and record ITMO Id;
    else (no)
      |Participating Party|
      stop
    
  endif

|Interoperating Party|


  while (Propose Use or Cancel txn) is (no)
  
    :Propose other
    txns on ITMOs;
      note left
      Other txns such as
      transfers, updates, ...
      end note
    |Interoperability\nHub|
    :Validate and
    facilitate
    other txns;
    |Interoperating Party|
    :Finalise other
    txns on ITMOs;
  endwhile (yes)
    |Interoperability\nHub|
    :Validate and
    facilitate
    Use or Cancel
    txns;
    |Interoperating Party|
    :Finalise Use or
    Cancel txns;
    stop


@enduml
