@startuml Overview

skinparam dpi 300
skinparam monochrome true
skinparam shadowing true
skinparam defaultTextAlignment center

node CARP {
    component "Submission portal" as sp
}

file "AEF" as aef1
file "AEF" as aef2
file "AEF" as aef3

node "International Registry" {
component "**Interoperability Hub**\n---\nApplies guidance" as h

component "**Registry Section 1**\n---\nMay apply guidance" as rs1
component "**Registry Section 2**\n---\nMay apply guidance" as rs2

rs1 <--> h #line.dotted
rs2 <--> h #line.dotted
}

node "**Registry 1**\n---\nApplies guidance" as r1
node "**Registry 2**\n---\nApplies guidance" as r2
node "**Registry 3**\n---\nDoes not apply guidance" as r3
node "**Article 6.4 Registry**\n---\nMay apply guidance" as a6r

r1 <-up-> h
r2 <-up-> h
a6r <-up-> h #line.dotted

r1 -down-> aef1 
r2 -down-> aef2 
r3 -down-> aef3 

aef1 -down-> sp #line.dotted
aef2 -down-> sp #line.dotted
aef3 -down-> sp #line.dotted

@enduml

