@startuml Transaction State Chart

skinparam dpi 300
skinparam monochrome false
skinparam shadowing true

top to bottom direction
hide empty description

state "Ongoing" as ip

State ip {
  [*] -[bold,#green]> Proposed
  Proposed -[bold,#green]-> Validated 
  Proposed -[#red]-> Invalidated

  Validated -[bold,#green]-> Accepted
  Validated -[#red]-> Rejected
}

State Finalized {
  Accepted -[bold,#green]-> Completed
  Invalidated -[#red]-> Terminated : / Reason
  Rejected -[#red]-> Terminated : / Reason
  ip -[#red]-> Terminated : / Time-out\n[> 24-hours] 
  Completed -[dashed,#red]-> Terminated : [Reversal agreed]\n/ Reason
}
@enduml
