@startuml

skinparam dpi 300
skinparam monochrome true
skinparam shadowing true
hide empty description

state Receiving_Registry {
 state "Proposed" as pr
 state "Validated" as vr
 state "Accepted" as ar
 state "Rejected" as rr
 state "Completed" as cr
 state "Terminated" as tr
 
 pr --> vr: [Automatic]
 vr --> ar
 vr --> rr
 ar --> cr: [Automatic]
 rr --> tr: [Automatic]
}

state Sending_Registry {
 state "Proposed" as ps
 state "Validated" as vs
 state "Invalidated" as is
 state "Accepted" as acs
 state "Rejected" as rs
 state "Completed" as cs
 state "Terminated" as ts

 state cs1 <<choice>>

 [*] -> ps
 rs --> ts
 vs --> acs
 vs --> rs
 acs --> cs
 is --> ts
 cs1 --> is: [Invalidated by the hub]
 cs1 --> vs: [Accepted or Rejected \nby the receiving registry]
 ps --> vs
 ps -> is
}

state Interoperability_Hub {
 state "Proposed" as ph
 state "Validated" as vh
 state "Invalidated" as ih
 state "Accepted" as ah
 state "Rejected" as rh
 state "Completed" as ch
 state "Terminated" as th

 state ch1 <<choice>>

 ph -> vh
 ph --> ih
 vh --> ah
 vh --> rh
 ah --> ch
 rh --> ch1
 ih --> ch1
 ch1 --> th
 ch --> [*]
 th --> [*]
}

ps --> ph: Proposal
vh --> pr: Proposal
ar --> ah: Acceptance
rr --> rh: Rejection
ah --> cs1: Acceptance
ih --> cs1: Invalidation
rh --> cs1: Rejection
cs --> ch: Completion
ts --> th: Termination
@enduml