@startuml Transaction State Chart

title TxnStatus Overview

skinparam dpi 300
skinparam monochrome false
skinparam shadowing true

top to bottom direction
hide empty description

state "Pending" as ip

State ip {
  [*] -[bold,#green]> Proposed
  Proposed -[bold,#green]-> Validated 
  Proposed -[#red]-> Invalidated

  Validated -[bold,#green]-> Accepted
  Validated -[#red]-> Rejected
}

State Finalized {
  Accepted -[bold,#green]-> Completed
  Invalidated -[#red]-> Terminated : / Invalid
  Rejected -[#red]-> Terminated : / Rejected
  
  Completed -[dashed,#red]-> Terminated : [Reversal agreed]\n/ Reason
  ip -[#red]-> Terminated : / Timed_out 
}


@enduml
