@startuml Transaction State Chart

title TxnStatus Overview

skinparam dpi 300
skinparam monochrome false
skinparam shadowing true

top to bottom direction
hide empty description

state "Pending" as ip

State ip {
  [*] -[bold,#green]> Proposed
  Proposed -[bold,#green]-> Validated 
  Proposed -[#red]-> Invalidated

  Validated -[bold,#green]-> Accepted
  Validated -[#red]-> Rejected
  Validated -[#red]-> Timed_out
  Invalidated -[#red]-> Timed_out
  Accepted -[#red]-> Timed_out
  Rejected -[#red]-> Timed_out
}

State Finalized {
  Accepted -[bold,#green]-> Completed
  Invalidated -[#red]-> Terminated : / Reason
  Rejected -[#red]-> Terminated : / Reason
  Timed_out -[#red]-> Terminated : / Timed_out 
  
  Completed -[dashed,#red]-> Terminated : [Reversal agreed]\n/ Reason
}
@enduml
