name: Run linters and build artifacts

on:
  - push

jobs:
  build:
    name: Run linters and build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
      - uses: ts-graphviz/setup-graphviz@v2
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint openapi.yaml --ruleset .spectral.yaml --format github-actions
      - run: spectral lint openapiCARP.yaml --ruleset .spectral.yaml --format github-actions
      - run: npm install -g @redocly/cli
      - run: redocly build-docs openapi.yaml --output=openapi.html
      - run: redocly build-docs openapiCARP.yaml --output=openapiCARP.html
      - run: java -jar plantuml-1.2025.0.jar "diagrams/*.puml" -tpng
      - run: java -jar plantuml-1.2025.0.jar "diagrams/*.puml" -tsvg
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install python-docx
      - run: python nom2docx.py -n CommonNomenclature.json -t CommonNomenclatureTemplate.docx -o CommonNomenclature.docx
      # Uncomment to generate PDF (takes ca 10 mins)
      - uses: jmservera/libreoffice-action@v0.2
        with:
          command: libreoffice --headless --invisible --convert-to pdf 'CommonNomenclature.docx' --outdir '.'
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            - openapi.html
            - openapiCARP.html
            - diagrams/*.png
            - diagrams/*.svg
            - CommonNomenclature.docx
            # Uncomment to generate PDF (takes ca 10 mins)
            #- CommonNomenclature.pdf
