name: Run linters and build artifacts on push

on:
  - push

jobs:
  build:
    name: Run linters and build artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint openapi.yaml --ruleset .spectral.yaml --format github-actions
      - run: npm install -g @redocly/cli
      - run: redocly build-docs openapi.yaml --output=openapi.html
      - run: java -jar plantuml-1.2025.0.jar "diagrams/*.puml" -tpng
      - run: java -jar plantuml-1.2025.0.jar "diagrams/*.puml" -tsvg
      - uses: EndBug/add-and-commit@v9
        with:
          add: |
            - openapi.html
            - diagrams/*.png
            - diagrams/*.svg
